config/routes.rb
GamecalculationDemo::Application.routes.draw do
  
  devise_for :models
  devise_for :users, :path => "usuarios", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  devise_for :admins, :controllers => { :sessions => "admins/sessions" }

  root :to => "home#news"
  
  match '/last_news',  :to => "home#news"
  match '/supported_leagues',  :to => "home#supported_leagues"
  match '/assistant',  :to => "home#assistant"
  match '/algoritms',  :to => "home#algoritms"
  match '/services',  :to => "home#services"
  match '/about',  :to => "home#about"
  
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

  resources :news do 
    as_routes 
  end
  
  resources :leagues_admin do 
    as_routes 
  end
  
  match 'leagues', :to => 'leagues#index'
  match 'leagues/:id', :to => 'leagues#details'

  resources :countries_admin do
    as_routes
  end
  
  match 'countries', :to => 'countries#index'

  resources :pages do
    as_routes
  end
  
  resources :bookmakers_admin do
    as_routes
  end
  
  match 'bookmakers', :to => 'bookmakers#index'
  
  resources :betting_predictions do
    as_routes
  end
  
  resources :settings do
    as_routes
  end
  
  resources :tasks do
    as_routes
  end
  
  resources :tests do
    as_routes
  end
  
  match 'football_matches', :to => 'football_matches#index'
  match 'football_matches/:id', :to => 'football_matches#details'
  
  resources :football_clubs_admin do
    as_routes
  end
  
  match 'football_clubs', :to => 'football_clubs#index'
  match 'football_clubs/:id', :to => 'football_clubs#details'
  
  resources :statistics
  

  
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/betting_prediction.rb
class BettingPrediction < ActiveRecord::Base
  belongs_to :football_match
  belongs_to :bookmaker
end

app/models/bookmaker.rb
class Bookmaker < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/football_club.rb
class FootballClub < ActiveRecord::Base
end

app/models/football_match.rb
class FootballMatch < ActiveRecord::Base
  has_many :betting_prediction
  has_one :prediction
end

app/models/league.rb
class League < ActiveRecord::Base
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
  belongs_to :football_match
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/statistics.rb
class Statistics < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  after_create :send_registration_confirmation_email
  
  def send_registration_confirmation_email
    @user = User.find_by_id self.id
    UserMailer.registration_confirmation(@user).deliver
  end
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base

  layout "frontend"
  require 'rss'
  require 'nokogiri'

  def index
  end
  
  def news
    @rss = RSS::Parser.parse(open('http://www.bundesliga.com/rss/en/liga/rss_news.xml').read, false)
  end

  def supported_leagues
  end
  
  def assistant
  end
  
  def algoritms
  end
  
  def services
  end
      
  def about
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_filter :authenticate_user!
  
  layout "backend"
  
  active_scaffold :news do |conf|
    config.label = "News"
    config.columns = [:title, :description, :image, :body, :is_show]
    list.sorting = {:created_at => 'DESC'}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GamecalculationDemo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BetAssistantDemo Backend</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <% if controller.controller_name ==  'bookmakers_admin' || controller.controller_name == 'settings' || controller.controller_name == 'news' || controller.controller_name == 'pages' || controller.controller_name == 'football_clubs_admin' || controller.controller_name == 'leagues_admin' || controller.controller_name == 'tests' || controller.controller_name == 'tasks' || controller.controller_name == 'countries_admin' %>
    <%= stylesheet_link_tag :active_scaffold %>
    <%= javascript_include_tag :active_scaffold %>
  <% end %>
  <%= csrf_meta_tags %>
</head>
<body>
  <center>
    <div id="logo_block">
      <a href="/">
        <img src="/images/logo.png" alt="bet assistant Alpha">
        <span class="logo_demo">alpha</span>
      </a>
      
      <div id="login_block">
        <% if user_signed_in? %>
          Signed in as <b><%= current_user.email %></b>.
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "login" %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => "register" %> | <%= link_to "Sign in", new_user_session_path, :class => "login" %>
        <% end %>
      </div>
    </div>
    <div id="admin_menu">
      <div class="item">
        <a href="/news">News</a>
      </div>
      <div class="item">
        <a href="/pages">Pages</a>
      </div>
      <div class="item">
        <a href="/countries_admin">Countries</a>
      </div>
      <div class="item">
        <a href="/leagues_admin">Leagues</a>
      </div>
      <div class="item">
        <a href="/football_clubs_admin">Clubs</a>
      </div>
      <div class="item">
        <a href="/bookmakers_admin">Bookmakers</a>
      </div>      
      <div class="item">
        <a href="/tasks">Tasks</a>
      </div>
      <div class="item">
        <a href="/tests">Tests</a>
      </div>
    </div>
    <div class="clear"></div>
    <div id="backend_content">
      <div id="backend_wrapper">
        <%= yield %>
      </div>
      <div class="clear"></div>
    </div>
    <div id="footer">
      <div id="footer_menu">
        <a href="/last_news">News</a> | <a href="/leagues">Leagues</a> | <a href="/football_clubs">Football Clubs</a> | <a href="/football_matches">Matches</a> | <a href="/bookmakers">Bookmakers</a> | <a href="/statistics">Statistics</a>  | <a href="/about">About</a>
      </div>
      <div class="copyright">
        &copy; 2011 <b>bet</b> assistant
      </div>  
    </div>
  </center>
</body>
</html>

app/views/layouts/frontend.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BetAssistant</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%if request.path == "" %>
    <script type="text/javascript">
      $(document).ready(function() {
        $('#slider').s3Slider({
          timeOut: 3000
        });
      });
    </script>
  <% end %>
  <center>
  <div id="main">
    <div id="header">
      <div id="logo_block">
        <a href="/">
          <img src="/images/logo.png" alt="bet assistant Alpha">
          <span class="logo_demo">alpha</span>
        </a>
        <div id="login_block">
          <% if user_signed_in? %>
            Signed in as <b><%= link_to "#{current_user.email}", "/news", :class => "login" %></b>.
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "login" %>
          <% else %>
            <!-- <%= link_to "Sign up", new_user_registration_path, :class => "register" %> | <%= link_to "Sign in", new_user_session_path, :class => "login" %> -->
          <% end %>
        </div>
      </div>
      <%if request.path == "" %>
        <div id="slider">
          <ul id="sliderContent">
            <li class="sliderImage">
                  <a href=""><img src="/images/home/ger3.jpg" alt="1" /></a>
                  <span class="top"><strong>Bundes League</strong></span>
              </li>
              <li class="sliderImage">
                  <a href=""><img src="/images/home/eng2.jpg" alt="2" /></a>
                  <span class="top"><strong>Premier League</strong></span>
              </li>
              <li class="sliderImage">
                  <img src="/images/home/spa1.jpg" alt="4" />
                  <span class="bottom"><strong>Primera</strong></span>
              </li>
              <li class="sliderImage">
                  <img src="/images/home/ita5.jpg" alt="5" />
                  <span class="top"><strong>Serie A</strong></span>
              </li>
              <li class="sliderImage">
                  <img src="/images/home/fra5.jpg" alt="3" />
                  <span class="bottom"><strong>League 1</strong></span>
              </li>
              <li class="sliderImage">
                  <img src="/images/home/ned4.jpg" alt="5" />
                  <span class="top"><strong>Eredivisie</strong></span>
              </li>
              <div class="clear sliderImage"></div>
          </ul>
        </div>
        <!-- // slider -->
      <% end %>
      <center>
      <div id="frontend_menu">
        <div class="item">
          <a href="/last_news">News</a>
        </div>
        <div class="item">
          <%= link_to "Leagues", leagues_path %>
        </div>
        <div class="item">
          <%= link_to "Football Clubs", football_clubs_path %>
        </div>
        <div class="item">
          <%= link_to "Matches", football_matches_path %>
        </div>
        <div class="item">
          <%= link_to "Bookmakers", bookmakers_path %>
        </div>
        <div class="item">
          <%= link_to "Statistics", statistics_path %>
        </div>
        <div class="item">
          <a href="/about">About</a>
        </div>
        <div class="item">
          <%= link_to "Setup", new_user_session_path %>          
        </div>
      </div>
      </center>

    </div>
    <div id="backend_content">
      <div id="backend_wrapper">
      
        <%= yield %>
        
      </div>
      <div class="clear"></div>
    </div>
    <div id="footer">
      <div id="footer_menu">
        <a href="/last_news">News</a> | <a href="/leagues">Leagues</a> | <a href="/football_clubs">Football Clubs</a> | <a href="/football_matches">Matches</a> | <a href="/bookmakers">Bookmakers</a> | <a href="/statistics">Statistics</a>  | <a href="/about">About</a>
      </div>
      <div class="copyright">
        &copy; 2011 <b>bet</b> assistant
      </div>  
    </div>
  </div>
  </center>
</body>
</html>